### ISSUE TITLE
Doesn't seem to run tests

### ISSUE THREAD

**Issue by marvinhagemeister** [vadimdemedes/trevor#39]
Thanks for creating an awesome project! That'd really help with a package I maintain at work (https://github.com/sevenval/eslint-config-sevenval). But somehow it doesn't seem like trevor actually runs the tests, because the command immediately exists with:

```bash
$ trevor

   ✖  6:  error
   ✖  7:  error
```

The `.travis.yml` in question:

```yml
language: node_js
notifications:
  email: false
cache:
  directories:
    - node_modules
node_js:
  - 6
  - 7
script:
  - npm test
```

**Comment by gdams** [comment]
I'm getting the same failures with my `.travis.yml`

**Comment by sanex3339** [comment]
```
   ✖      4:  error
   ✖      5:  error
   ✖      6:  error
   ✖  4.3.0:  error
   ✖  7.4.0:  error
```

```
sudo: false
language: node_js

node_js:
  - "4.3.0"
  - "4"
  - "5"
  - "6"
  - "stable"

cache:
  yarn: true
  directories:
    - node_modules

script: "yarn run travis"

after_success:
  - yarn run test:coveralls
  - rm -rf ./coverage
```
