### ISSUE TITLE
Problem with yarn?

### ISSUE THREAD

**Issue by luruke** [vadimdemedes/trevor#48]
Hi there, I gave a try to trevor on an existing project using travis as CI.
(https://github.com/luruke/barba.js/tree/v2-dev)

I got this error, probably related to the use of `yarn`.

```
╰─$ trevor

 ✖ 7.4.0: error

 ✖ 7.4.0:
 container_linux.go:247: starting container process caused "exec: \"yarn\": executable file not found in $PATH"
 docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"yarn\": executable file not found in $PATH".
```

my travis.yml

```yml
language: node_js
sudo: required
dist: trusty
before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb
script:
 - yarn run build
 - yarn test
 - yarn run coveralls
 - yarn run e2e-sauce
addons:
  sauce_connect: true
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f122fc8ebfa457305f12
    on_success: change
    on_failure: always
    on_start: never
```
