### ISSUE TITLE
Slow `building environment` state

### ISSUE THREAD

**Issue by sanex3339** [vadimdemedes/trevor#50]
How fast `docker` should run `building environment` state?

For me on MacBook air 2015 (8gb ram) with one container (node 7.4.0) it takes 1:50 min, for me it looks very slow.

With 5 containers time increases greatly.

**Comment by gokaygurcan** [comment]
Here's my .travis.yml and the results on Windows 10 Enterprise [Version 10.0.10240] :

```yaml
language: node_js

node_js:
  - '7'
  - '6'
  - '4'

before_install:
  - npm install -g npm
  - npm install -g xo

script:
  - xo
```

```bash
PS C:\Users\gokaygurcan\Projects\trevor-test> Measure-Command {trevor}


Days              : 0
Hours             : 0
Minutes           : 6
Seconds           : 19
Milliseconds      : 256
Ticks             : 3792569434
TotalDays         : 0,00438954795601852
TotalHours        : 0,105349150944444
TotalMinutes      : 6,32094905666667
TotalSeconds      : 379,2569434
TotalMilliseconds : 379256,9434
```

As a sum, 6m 19s with 3 different versions. That makes ~2m for each like yours. My virtual machine's specs are 1 GB memory and 1 CPU core up to 100% cap btw. 

I'll try on macOS with same specs and update the comment tonight.
