### ISSUE TITLE
Fails on node version `lts/*`

### ISSUE THREAD

**Issue by mightyiam** [vadimdemedes/trevor#61]
```
➜  cyclejs-web-components git:(master) ✗ trevor                                                                      

 ◌ 7.6.0: downloading base image
 ✖ lts/*: error
Error: ENOENT: no such file or directory, unlink '/home/shahar/src/cyclejs-web-components/.lts/*.dockerfile'
➜  cyclejs-web-components git:(master) ✗
```

```yml
language: node_js
node_js:
  - node
  - lts/*
```
